#  Indexing

In [3]:
import numpy as np

var=np.array([1,2,3,4,5,6,7,8])
print(var[2])

3


In [8]:
var1=np.array([[1,2],[4,5]])

print(var1.ndim)
print()
print(var1)

print(var1[1,1])

2

[[1 2]
 [4 5]]
5


In [13]:
var2=np.array([[[1,2],[24,65]]])

print(var2)
print()
print(var2.ndim)

print(var2[0,1,1])

[[[ 1  2]
  [24 65]]]

3
65


#  Slicing


In [18]:
varr=np.array([1,2,3,4,5,6,7,8,0])

print(varr[0:7:4])
print(var[::2])

[1 5]
[1 3 5 7]


In [24]:
vrd=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(vrd[2,0:])
print()
print(vrd.ndim)

[ 9 10 11 12]

2
