In [4]:
import numpy as np

var=np.array([1,2,3,4,5])
var1=np.array([6,7,8,9,10])

ar=np.concatenate((var,var1))

print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
varr=np.array([[1,2],[4,5]])
varr1=np.array([[6,7],[9,10]])

print(varr)
print()
print(varr1)
print()


arr=np.concatenate((varr,varr1),axis=1)
print(arr)

[[1 2]
 [4 5]]

[[ 6  7]
 [ 9 10]]

[[ 1  2  6  7]
 [ 4  5  9 10]]


In [15]:
rows=np.hstack((varr,varr1))
print(rows)

print()
col=np.vstack((varr,varr1))
print(col)
print()


dep=np.dstack((varr,varr1))
print(dep)

[[ 1  2  6  7]
 [ 4  5  9 10]]

[[ 1  2]
 [ 4  5]
 [ 6  7]
 [ 9 10]]

[[[ 1  6]
  [ 2  7]]

 [[ 4  9]
  [ 5 10]]]


# Split

In [26]:
sp=np.array([1,2,3,4,5,6,7])

arrr=np.array_split(var,3)
print(arrr)

[array([1, 2]), array([3, 4]), array([5])]


In [24]:
vad=np.array([[1,2],[3,4],[5,6]])

vadarr=np.array_split(vad,3,axis=1)
print(vadarr)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
