# Search


In [6]:
import numpy as np

var = np.array([1,2,3,4,2,3,4,3,4,3,2,2,9])

x=np.where((var%2)==0)
print(x)

(array([ 1,  3,  4,  6,  8, 10, 11], dtype=int64),)


In [7]:
var1=np.array([1,2,3,4,8,9])

x1=np.searchsorted(var1,[5,6,7],side="left")
print(x1)

print()
print(var1)

[4 4 4]

[1 2 3 4 8 9]


# Sort

In [8]:
varr=np.array([3,4,6,3,39,65,32,4,6,3,2])

np.sort(varr)

array([ 2,  3,  3,  3,  4,  4,  6,  6, 32, 39, 65])

In [9]:
var_3=np.array(["a","s","d","f"])

f=[True,False,False,True]

new_a=var_3[f]

print(new_a)

['a' 'f']


# Uniqe

In [10]:
varu=np.array([3,4,6,3,39,65,32,4,6,3,2])

unike=np.unique(var1,return_index=True,return_counts=True)

print(unike)

(array([1, 2, 3, 4, 8, 9]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([1, 1, 1, 1, 1, 1], dtype=int64))


# Resize

In [11]:
ra=np.array([1,2,3,4,5,4,6,64,64,3,4,44,34,32])

np.resize(ra,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  4,  6, 64],
       [64,  3,  4, 44],
       [34, 32,  1,  2]])

In [12]:
ra=np.array([1,2,3,4,5,4,6,64,64,3,4,44,34,32])

y=np.resize(ra,(4,4))

print(y.flatten())



[ 1  2  3  4  5  4  6 64 64  3  4 44 34 32  1  2]


# Flatten

In [15]:
print("flaten :",y.flatten())

print("ravel :",np.ravel(y,order="K"))

flaten : [ 1  2  3  4  5  4  6 64 64  3  4 44 34 32  1  2]
ravel : [ 1  2  3  4  5  4  6 64 64  3  4 44 34 32  1  2]
