In [6]:
import numpy as np

var=np.array([1,2,3,4,5])

print(var)

v=np.insert(var,2,23)
print(v)

[1 2 3 4 5]
[ 1  2 23  3  4  5]


In [11]:
var1=np.array([[1,2,3,4],[6,7,8,9]])
# print(var1)

v1=np.insert(var1,2,87,axis=1)
print(v1)

[[ 1  2 87  3  4]
 [ 6  7 87  8  9]]


# Delete

In [13]:
vard=np.array([1,2,3,4,5])

print(vard)
print()
x2=np.delete(vard)

[1 2 3 4 5]

