In [5]:
import numpy as np


var=np.matrix([[1,2],[1,2]])
var2=np.matrix([[1,2],[1,2]])


var

print(var.dot(var2))

[[3 6]
 [3 6]]


In [6]:
vars=np.matrix([[1,2],[1,2]])
print(np.swapaxes(var,0,1))

[[1 1]
 [2 2]]


# Inverse

In [10]:
var3=np.matrix([[1,4],[9,2]])
print(np.linalg.inv(var3))

[[-0.05882353  0.11764706]
 [ 0.26470588 -0.02941176]]


# Power

In [21]:
varp=np.matrix([[4,2],[1,2]])

print(np.linalg.matrix_power(varp,3))

[[84 60]
 [30 24]]


# Determinate

In [23]:
varpd=np.matrix([[4,2,3],[1,2,3],[1,2,4]])

print(np.linalg.det(varpd))

6.0
