# Numpy

In [13]:
import numpy as np

a=[2,3,4,5,6]
b=np.array(a)
print(b)

x = np.array([1,2,3,4])
print(x)
print(type(x))

[2 3 4 5 6]
[1 2 3 4]
<class 'numpy.ndarray'>


In [22]:
l=[]

for i in range(1,5):
    int_1=int(input("Enter the Number:"))
    l.append(int_1)
    
print(np.array(l))     2

Enter the Number:22
Enter the Number:2
Enter the Number:2
Enter the Number:22
[22  2  2 22]


# Creating array in NumPy

In [23]:
arr2=np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [26]:
arrn=np.array([1,2,3,4,5],ndim=10)
print(arrn)
print(arrn.ndim)

TypeError: array() got an unexpected keyword argument 'ndim'

In [6]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [10]:
%timeit [j**4 for j in range (1,9)]

667 ns ± 16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
%timeit np.arange(1,9)**4

2.84 µs ± 781 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
