#  1. Zero

In [7]:
import numpy as np

ar_zero=np.zeros(4)
ar_zero2=np.zeros((3,4))

print(ar_zero2)
print()
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0.]


# Ones

In [12]:
ar_one=np.ones(5)
print(ar_one)

print()



ar_one5=np.ones((5,6))
print(ar_one5)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# Empty

In [13]:
ar_em=np.empty(5)
print(ar_em)

[1. 1. 1. 1. 1.]


# Range

In [18]:
ar_ra=np.arange(43)
print(ar_ra)




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42]


# Diagonal Eye

In [20]:
ar_ey=np.eye(3)
print(ar_ey)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
ar_eye=np.eye(5,5)
print(ar_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# LineSpace

In [23]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
