# rand()

In [6]:
import numpy as np

var=np.random.rand(5)
print(var)

[0.04819352 0.94438344 0.89521468 0.58730649 0.48712134]


In [8]:
var1=np.random.rand(2,5)
var1

array([[0.77182762, 0.12064246, 0.69892788, 0.89601884, 0.07412753],
       [0.01705399, 0.8467503 , 0.59999674, 0.52680791, 0.8439932 ]])

# randf()

In [10]:
var2=np.random.ranf(5)
var2

array([0.99551813, 0.90059537, 0.43929321, 0.59122508, 0.73007257])

# randn()

In [11]:
var3=np.random.randn(5)
var3

array([ 0.69607785,  1.93555726,  1.27616764,  0.71860861, -1.01366261])

# randint()

In [12]:
var4=np.random.randint(2,20,5)
var4

array([14, 17, 11,  8, 19])