# Data Type

In [3]:
import numpy as np

var=np.array([1,2,3,4,5,6])
print("Data Typed :",var.dtype)

Data Typed : int32


In [4]:
var=np.array(["s","s","z"])
print("Data Typed :",var.dtype)

Data Typed : <U1


In [5]:
var=np.array(["s","s","z",1,3,4,5])
print("Data Typed :",var.dtype)

Data Typed : <U11


In [8]:
var=np.array([1,2,3,4,5],dtype=np.int8)
print("Data Type :",var.dtype)

Data Type : int8


In [9]:
va=np.array([1,2,3,4,5],dtype="f")
print("Data Type :",va.dtype)

Data Type : float32


# as a function

In [11]:
x2= np.array([1,2,3,4,5])

new =np.float32(x2)

print("Data Type :",x2.dtype)
print("Data Type :",new.dtype)

print(x2)
print(new)

Data Type : int32
Data Type : float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [12]:
x2= np.array([1,2,3,4,5])

new =np.float32(x2)
new_one=np.int_(new)


print("Data Type :",x2.dtype)
print("Data Type :",new.dtype)
print("Data Type :",new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type : int32
Data Type : float32
Data Type : int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [13]:
x3=np.array([1,3,4,6])

new_1=x3.astype(float)

print(x3)
print(new_1)

[1 3 4 6]
[1. 3. 4. 6.]
