# Arithmetic Operation

In [3]:
import numpy as np

var =np.array([1,2,3,4])
varadd=var+3

print("The Original value of the array :",var)
print(varadd)

The Original value of the array : [1 2 3 4]
[4 5 6 7]


In [4]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])

varnew=var1+var2
print(varnew)

[2 4 6 8]


In [5]:
var1 =np.array([1,2,3,4])


varnew=var1 % 3
print(varnew)

[1 2 0 1]


In [15]:
varr=np.array([1,2,3,4])


varnewr=np.reciprocal(varr)
print(varnewr)

[1 0 0 0]


# 2D Array

In [10]:
var21 =np.array([[1,2,3,4],[1,2,3,4]])
var22 =np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
print()


varadd = var21 * var21
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]


[[ 1  4  9 16]
 [ 1  4  9 16]]
